install.packages("rJava")
install.packages("UpSetR")
install.packages("tidyverse")
install.packages("venneuler")
install.packages("grid")
library(rJava)
library(UpSetR)
library(tidyverse)
library(venneuler)
library(grid)
library(pcadapt)
library(gridExtra)
hc1=read.pcadapt('/shire/zillur/hectors/plink1/merged.q20d20.bed')
hc1=pcadapt(hc1,K=20)
hb1=read.csv('/shire/zillur/hectors/plink1/merged.q20d20.bim',sep='\t',header = F)
hb1$V7=paste(hb1$V5,hb1$V6)

png('/shire/zillur/hectors/plink1/test_plot_2.png',width = 800,height = 1200)
p2=plot(hc1, option = "scores",i=2,j=1)+ggtitle(paste("Hector's data", length(hc1$af), 'SNPs'))
q1=qplot(hc1$af,geom = 'histogram',binwidth=0.01,xlab = 'allele frequency',ylab = 'count')
q2=qplot(hb1$V7,geom = 'bar',xlab='SNPs',ylab = 'count')+theme(axis.text.x=element_text(angle=90, hjust=1))
grid.arrange(q1,p2,q2)
dev.off()

hc1000g=read.pcadapt('/shire/zillur/hectors/plink1/hector1000g.bed')
hc1000g=pcadapt(hc1000g,K=20)
